export const ADD_NOTE = "notes/ADD_NOTE"
export const SET_SELECTED = "notes/SET_SELECTED"
export const SET_NOTES = "notes/SET_NOTES"
export const DELETE_NOTE = "notes/DELETE_NOTE"
export const SHOW_EDIT_FORM = "notes/SHOW_EDIT_FORM"
export const SHOW_ADD_FORM = "notes/SHOW_ADD_FORM"